# -*- coding: utf-8 -*-
"""digital_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGPOgKuOrAv-iIT_C9k7lZHkELPKfVW7
"""

!pip install kaggle -q

import os

!wget -q https://github.com/BIDS/BSDS500/archive/refs/heads/master.zip
!unzip -q master.zip
!ls BSDS500-master/

!ls BSDS500-master/BSDS500/data/

!ls BSDS500-master/BSDS500/data/images/

import numpy as np
import matplotlib.pyplot as plt
from skimage import io, color
from skimage.util import random_noise
import os

# Görüntü klasörü
img_dir = 'BSDS500-master/BSDS500/data/images/test/'

# Tüm görüntüleri listele
img_files = [f for f in os.listdir(img_dir) if f.endswith('.jpg')]
print(f"Test setinde {len(img_files)} görüntü var")

# Bir görüntü yükleyip göster
img_path = os.path.join(img_dir, img_files[0])
img = io.imread(img_path)
img_gray = color.rgb2gray(img)

plt.figure(figsize=(6,4))
plt.imshow(img_gray, cmap='gray')
plt.title('Örnek görüntü')
plt.axis('off')
plt.show()

print(f"Görüntü boyutu: {img_gray.shape}")

def add_gaussian_noise(image, sigma):
    """
    Görüntüye Gaussian gürültü ekler.
    sigma: gürültü standart sapması (0-255 ölçeğinde)
    """
    # skimage random_noise 0-1 aralığında çalışır
    noise_var = (sigma / 255.0) ** 2
    noisy = random_noise(image, mode='gaussian', var=noise_var)
    return noisy

# Test edelim - 3 farklı noise seviyesi
sigma_levels = [5, 10, 25]

fig, axes = plt.subplots(1, 4, figsize=(16, 4))

axes[0].imshow(img_gray, cmap='gray')
axes[0].set_title('Orijinal')
axes[0].axis('off')

for i, sigma in enumerate(sigma_levels):
    noisy_img = add_gaussian_noise(img_gray, sigma)
    axes[i+1].imshow(noisy_img, cmap='gray')
    axes[i+1].set_title(f'σ = {sigma}')
    axes[i+1].axis('off')

plt.suptitle('Gaussian Noise Seviyeleri')
plt.tight_layout()
plt.show()

from skimage.feature import canny
from skimage.filters import sobel, threshold_otsu
from skimage.filters import gaussian
import time

# ── Baseline 1: Sobel ──────────────────────────────────────────────
def sobel_detector(image):
    start = time.time()
    edge_map = sobel(image)
    # Sobel çıktısını binary'ye çevir (Otsu ile threshold)
    thresh = threshold_otsu(edge_map)
    binary = edge_map > thresh
    runtime = time.time() - start
    return binary, runtime

# ── Baseline 2: Standard Canny (sabit parametreler) ────────────────
def standard_canny(image, sigma=1.0, low_threshold=0.05, high_threshold=0.15):
    start = time.time()
    edge_map = canny(image, sigma=sigma,
                     low_threshold=low_threshold,
                     high_threshold=high_threshold)
    runtime = time.time() - start
    return edge_map, runtime

# ── Baseline 3: Otsu-Canny (Medina-Carnicer et al., 2011) ──────────
def otsu_canny(image, sigma=1.0):
    start = time.time()
    # Önce smooth et
    smoothed = gaussian(image, sigma=sigma)
    # Gradient magnitude hesapla
    grad = sobel(smoothed)
    # Gradient üzerine Otsu uygula
    high_threshold = threshold_otsu(grad)
    low_threshold = 0.5 * high_threshold
    edge_map = canny(image, sigma=sigma,
                     low_threshold=low_threshold,
                     high_threshold=high_threshold)
    runtime = time.time() - start
    return edge_map, runtime

# ── Test: bir görüntü üzerinde dene ────────────────────────────────
noisy_img = add_gaussian_noise(img_gray, sigma=25)

sobel_edges, _ = sobel_detector(noisy_img)
canny_edges, _ = standard_canny(noisy_img)
otsu_edges, _ = otsu_canny(noisy_img)

fig, axes = plt.subplots(1, 4, figsize=(16, 4))
axes[0].imshow(noisy_img, cmap='gray')
axes[0].set_title('Gürültülü Görüntü (σ=25)')
axes[0].axis('off')

axes[1].imshow(sobel_edges, cmap='gray')
axes[1].set_title('Sobel')
axes[1].axis('off')

axes[2].imshow(canny_edges, cmap='gray')
axes[2].set_title('Standard Canny')
axes[2].axis('off')

axes[3].imshow(otsu_edges, cmap='gray')
axes[3].set_title('Otsu-Canny')
axes[3].axis('off')

plt.suptitle('Baseline Yöntemler (σ_noise=25)')
plt.tight_layout()
plt.show()

def estimate_noise(image):
    """
    MAD tabanlı noise tahmini.
    Laplacian residual üzerinden sigma_est hesaplar.
    """
    smoothed = gaussian(image, sigma=1.0)
    residual = image - smoothed
    median = np.median(residual)
    sigma_est = np.median(np.abs(residual - median)) / 0.6745
    sigma_est = max(sigma_est, 1.0 / 255.0)  # çok küçük değerleri önle
    return sigma_est

def noise_calibrated_canny(image, alpha=0.8, beta=0.4, gamma=2.0, k=0.5):
    """
    Proposed method: Noise-Calibrated Canny (NCC)
    """
    start = time.time()

    # Stage 1: Noise estimation
    sigma_est = estimate_noise(image)

    # Stage 2: Adaptive Gaussian smoothing
    sigma_g = k * sigma_est * 255  # 0-1 ölçeğinden 0-255'e
    sigma_g = np.clip(sigma_g, 0.5, 3.0)
    smoothed = gaussian(image, sigma=sigma_g)

    # Stage 3: Gradient computation
    grad = sobel(smoothed)
    mu_grad = np.mean(grad)

    # Stage 4: Noise-proportional threshold selection
    # T_high = alpha * (mu_grad + gamma * sigma_est)
    # T_low  = beta * T_high
    t_high = alpha * (mu_grad + gamma * sigma_est)
    t_low  = beta * t_high

    edge_map = canny(image, sigma=sigma_g,
                     low_threshold=t_low,
                     high_threshold=t_high)

    runtime = time.time() - start
    return edge_map, runtime, sigma_est, sigma_g, t_high, t_low

# Test edelim
ncc_edges, _, sigma_est, sigma_g, t_high, t_low = noise_calibrated_canny(noisy_img)

print(f"σ_est: {sigma_est:.4f}")
print(f"σ_g (smoothing): {sigma_g:.4f}")
print(f"T_high: {t_high:.4f}")
print(f"T_low:  {t_low:.4f}")

fig, axes = plt.subplots(1, 5, figsize=(20, 4))
axes[0].imshow(noisy_img, cmap='gray')
axes[0].set_title('Gürültülü (σ=25)')
axes[0].axis('off')

axes[1].imshow(sobel_edges, cmap='gray')
axes[1].set_title('Sobel')
axes[1].axis('off')

axes[2].imshow(canny_edges, cmap='gray')
axes[2].set_title('Standard Canny')
axes[2].axis('off')

axes[3].imshow(otsu_edges, cmap='gray')
axes[3].set_title('Otsu-Canny')
axes[3].axis('off')

axes[4].imshow(ncc_edges, cmap='gray')
axes[4].set_title('NCC (Proposed)')
axes[4].axis('off')

plt.suptitle('Tüm Yöntemler (σ_noise=25)')
plt.tight_layout()
plt.show()

def estimate_noise(image):
    """
    MAD tabanlı noise tahmini.
    Laplacian residual üzerinden sigma_est hesaplar.
    """
    smoothed = gaussian(image, sigma=1.0)
    residual = image - smoothed
    median = np.median(residual)
    sigma_est = np.median(np.abs(residual - median)) / 0.6745
    sigma_est = max(sigma_est, 1.0 / 255.0)  # çok küçük değerleri önle
    return sigma_est

def noise_calibrated_canny(image, alpha=0.8, beta=0.4, gamma=2.0, k=0.5):
    """
    Proposed method: Noise-Calibrated Canny (NCC)
    """
    start = time.time()

    # Stage 1: Noise estimation
    sigma_est = estimate_noise(image)

    # Stage 2: Adaptive Gaussian smoothing
    sigma_g = k * sigma_est * 255  # 0-1 ölçeğinden 0-255'e
    sigma_g = np.clip(sigma_g, 0.5, 3.0)
    smoothed = gaussian(image, sigma=sigma_g)

    # Stage 3: Gradient computation
    grad = sobel(smoothed)
    mu_grad = np.mean(grad)

    # Stage 4: Noise-proportional threshold selection
    # T_high = alpha * (mu_grad + gamma * sigma_est)
    # T_low  = beta * T_high
    t_high = alpha * (mu_grad + gamma * sigma_est)
    t_low  = beta * t_high

    edge_map = canny(image, sigma=sigma_g,
                     low_threshold=t_low,
                     high_threshold=t_high)

    runtime = time.time() - start
    return edge_map, runtime, sigma_est, sigma_g, t_high, t_low

# Test edelim
ncc_edges, _, sigma_est, sigma_g, t_high, t_low = noise_calibrated_canny(noisy_img)

print(f"σ_est: {sigma_est:.4f}")
print(f"σ_g (smoothing): {sigma_g:.4f}")
print(f"T_high: {t_high:.4f}")
print(f"T_low:  {t_low:.4f}")

fig, axes = plt.subplots(1, 5, figsize=(20, 4))
axes[0].imshow(noisy_img, cmap='gray')
axes[0].set_title('Gürültülü (σ=25)')
axes[0].axis('off')

axes[1].imshow(sobel_edges, cmap='gray')
axes[1].set_title('Sobel')
axes[1].axis('off')

axes[2].imshow(canny_edges, cmap='gray')
axes[2].set_title('Standard Canny')
axes[2].axis('off')

axes[3].imshow(otsu_edges, cmap='gray')
axes[3].set_title('Otsu-Canny')
axes[3].axis('off')

axes[4].imshow(ncc_edges, cmap='gray')
axes[4].set_title('NCC (Proposed)')
axes[4].axis('off')

plt.suptitle('Tüm Yöntemler (σ_noise=25)')
plt.tight_layout()
plt.show()

def compute_precision_recall(pred_edges, gt_edges, tolerance=2):
    """
    Precision ve Recall hesaplar.
    tolerance: kaç piksel tolerans (BSDS standardı: 2px)
    """
    from scipy.ndimage import binary_dilation

    # Ground truth'u biraz genişlet (tolerans için)
    gt_dilated = binary_dilation(gt_edges, iterations=tolerance)
    pred_dilated = binary_dilation(pred_edges, iterations=tolerance)

    # Precision: tahmin edilen kenarların ne kadarı gerçek
    if pred_edges.sum() == 0:
        precision = 0.0
    else:
        precision = (pred_edges & gt_dilated).sum() / pred_edges.sum()

    # Recall: gerçek kenarların ne kadarı bulundu
    if gt_edges.sum() == 0:
        recall = 0.0
    else:
        recall = (gt_edges & pred_dilated).sum() / gt_edges.sum()

    # F-measure
    if precision + recall == 0:
        f_measure = 0.0
    else:
        f_measure = 2 * precision * recall / (precision + recall)

    return precision, recall, f_measure

def load_ground_truth(img_filename, gt_dir):
    """
    BSDS500 ground truth'u yükler (.mat dosyası)
    """
    import scipy.io as sio

    img_id = img_filename.replace('.jpg', '')
    gt_path = os.path.join(gt_dir, img_id + '.mat')

    if not os.path.exists(gt_path):
        return None

    mat = sio.loadmat(gt_path)
    # BSDS500'de birden fazla annotator var, ortalamasını al
    gt_data = mat['groundTruth']
    boundaries = []
    for i in range(gt_data.shape[1]):
        boundary = gt_data[0, i]['Boundaries'][0, 0]
        boundaries.append(boundary)

    # Annotator'ların union'ı
    gt_combined = np.zeros_like(boundaries[0], dtype=bool)
    for b in boundaries:
        gt_combined = gt_combined | (b > 0)

    return gt_combined

# Test edelim - ground truth yükle
gt_dir = 'BSDS500-master/BSDS500/data/groundTruth/test/'
gt = load_ground_truth(img_files[0], gt_dir)

if gt is not None:
    print(f"Ground truth yüklendi: {gt.shape}")
    plt.figure(figsize=(6,4))
    plt.imshow(gt, cmap='gray')
    plt.title('Ground Truth')
    plt.axis('off')
    plt.show()
else:
    print("Ground truth bulunamadı")

def run_benchmark(img_files, img_dir, gt_dir, sigma_levels=[5, 10, 25], n_images=50):
    """
    Tüm yöntemleri tüm noise seviyelerinde değerlendirir.
    """
    results = {
        'sobel': {s: [] for s in sigma_levels},
        'standard_canny': {s: [] for s in sigma_levels},
        'otsu_canny': {s: [] for s in sigma_levels},
        'ncc': {s: [] for s in sigma_levels},
    }
    runtimes = {
        'sobel': [], 'standard_canny': [], 'otsu_canny': [], 'ncc': []
    }

    # İlk n_images kadar görüntü kullan
    selected_files = img_files[:n_images]

    for i, fname in enumerate(selected_files):
        print(f"İşleniyor: {i+1}/{n_images} - {fname}", end='\r')

        # Ground truth yükle
        gt = load_ground_truth(fname, gt_dir)
        if gt is None:
            continue

        # Orijinal görüntüyü yükle
        img = io.imread(os.path.join(img_dir, fname))
        img_gray = color.rgb2gray(img)

        for sigma in sigma_levels:
            noisy = add_gaussian_noise(img_gray, sigma)

            # Sobel
            edges, rt = sobel_detector(noisy)
            p, r, f = compute_precision_recall(edges, gt)
            results['sobel'][sigma].append((p, r, f))
            if sigma == sigma_levels[0]:
                runtimes['sobel'].append(rt)

            # Standard Canny
            edges, rt = standard_canny(noisy)
            p, r, f = compute_precision_recall(edges, gt)
            results['standard_canny'][sigma].append((p, r, f))
            if sigma == sigma_levels[0]:
                runtimes['standard_canny'].append(rt)

            # Otsu-Canny
            edges, rt = otsu_canny(noisy)
            p, r, f = compute_precision_recall(edges, gt)
            results['otsu_canny'][sigma].append((p, r, f))
            if sigma == sigma_levels[0]:
                runtimes['otsu_canny'].append(rt)

            # NCC (Proposed)
            edges, rt, _, _, _, _ = noise_calibrated_canny(noisy)
            p, r, f = compute_precision_recall(edges, gt)
            results['ncc'][sigma].append((p, r, f))
            if sigma == sigma_levels[0]:
                runtimes['ncc'].append(rt)

    print("\nTamamlandı!")
    return results, runtimes

# Çalıştır (50 görüntü, biraz sürebilir)
results, runtimes = run_benchmark(img_files, img_dir, gt_dir, n_images=50)
print("Benchmark tamamlandı.")

def print_results_table(results, runtimes):
    """
    Sonuçları düzenli tablo formatında yazdırır.
    """
    methods = {
        'sobel': 'Sobel',
        'standard_canny': 'Standard Canny',
        'otsu_canny': 'Otsu-Canny',
        'ncc': 'NCC (Proposed)'
    }
    sigma_levels = [5, 10, 25]

    print(f"{'Yöntem':<20} {'σ':>5} {'Precision':>10} {'Recall':>10} {'F-measure':>10}")
    print("-" * 60)

    for method_key, method_name in methods.items():
        for sigma in sigma_levels:
            vals = results[method_key][sigma]
            avg_p = np.mean([v[0] for v in vals])
            avg_r = np.mean([v[1] for v in vals])
            avg_f = np.mean([v[2] for v in vals])
            print(f"{method_name:<20} {sigma:>5} {avg_p:>10.4f} {avg_r:>10.4f} {avg_f:>10.4f}")
        print()

    print("\nOrtalama Runtime (ms/görüntü):")
    print("-" * 40)
    for method_key, method_name in methods.items():
        avg_rt = np.mean(runtimes[method_key]) * 1000
        print(f"{method_name:<20}: {avg_rt:.2f} ms")

print_results_table(results, runtimes)

def plot_fmeasure_comparison(results):
    sigma_levels = [5, 10, 25]
    methods = {
        'sobel': 'Sobel',
        'standard_canny': 'Standard Canny',
        'otsu_canny': 'Otsu-Canny',
        'ncc': 'NCC (Proposed)'
    }
    colors = ['blue', 'green', 'orange', 'red']
    markers = ['o', 's', '^', 'D']

    plt.figure(figsize=(8, 5))

    for (method_key, method_name), color, marker in zip(methods.items(), colors, markers):
        f_scores = []
        for sigma in sigma_levels:
            vals = results[method_key][sigma]
            avg_f = np.mean([v[2] for v in vals])
            f_scores.append(avg_f)

        lw = 2.5 if method_key == 'ncc' else 1.5
        plt.plot(sigma_levels, f_scores,
                 label=method_name, color=color,
                 marker=marker, linewidth=lw,
                 markersize=8)

    plt.xlabel('Noise Level (σ)', fontsize=12)
    plt.ylabel('F-measure', fontsize=12)
    plt.title('F-measure vs Noise Level', fontsize=13)
    plt.legend(fontsize=10)
    plt.xticks(sigma_levels)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('fmeasure_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()

plot_fmeasure_comparison(results)

def plot_visual_comparison(img_gray, sigma_levels=[5, 10, 25]):
    """
    Her noise seviyesi için tüm yöntemlerin edge map karşılaştırması.
    """
    methods = {
        'Sobel': sobel_detector,
        'Standard Canny': standard_canny,
        'Otsu-Canny': otsu_canny,
    }

    fig, axes = plt.subplots(len(sigma_levels), 5, figsize=(20, 12))

    for row, sigma in enumerate(sigma_levels):
        noisy = add_gaussian_noise(img_gray, sigma)

        # Noisy görüntü
        axes[row, 0].imshow(noisy, cmap='gray')
        axes[row, 0].set_title(f'Noisy (σ={sigma})', fontsize=9)
        axes[row, 0].axis('off')

        # Sobel
        edges, _ = sobel_detector(noisy)
        axes[row, 1].imshow(edges, cmap='gray')
        axes[row, 1].set_title('Sobel', fontsize=9)
        axes[row, 1].axis('off')

        # Standard Canny
        edges, _ = standard_canny(noisy)
        axes[row, 2].imshow(edges, cmap='gray')
        axes[row, 2].set_title('Standard Canny', fontsize=9)
        axes[row, 2].axis('off')

        # Otsu-Canny
        edges, _ = otsu_canny(noisy)
        axes[row, 3].imshow(edges, cmap='gray')
        axes[row, 3].set_title('Otsu-Canny', fontsize=9)
        axes[row, 3].axis('off')

        # NCC
        edges, _, _, _, _, _ = noise_calibrated_canny(noisy)
        axes[row, 4].imshow(edges, cmap='gray')
        axes[row, 4].set_title('NCC (Proposed)', fontsize=9)
        axes[row, 4].axis('off')

    plt.suptitle('Visual Comparison Across Noise Levels', fontsize=13)
    plt.tight_layout()
    plt.savefig('visual_comparison.png', dpi=150, bbox_inches='tight')
    plt.show()

# İlk görüntü üzerinde çalıştır
plot_visual_comparison(img_gray)

def ncc_ablation_A(image, alpha=0.8, beta=0.4, gamma=2.0):
    """NCC-A: Sadece adaptive smoothing, sabit Otsu threshold"""
    start = time.time()
    sigma_est = estimate_noise(image)
    sigma_g = np.clip(0.5 * sigma_est * 255, 0.5, 3.0)
    smoothed = gaussian(image, sigma=sigma_g)
    grad = sobel(smoothed)
    # Threshold: Otsu (sabit, noise-aware değil)
    t_high = threshold_otsu(grad)
    t_low = 0.5 * t_high
    edges = canny(image, sigma=sigma_g,
                  low_threshold=t_low, high_threshold=t_high)
    return edges, time.time() - start

def ncc_ablation_B(image, alpha=0.8, beta=0.4, gamma=2.0):
    """NCC-B: Sabit smoothing, sadece adaptive threshold"""
    start = time.time()
    sigma_est = estimate_noise(image)
    sigma_g = 1.0  # sabit
    smoothed = gaussian(image, sigma=sigma_g)
    grad = sobel(smoothed)
    mu_grad = np.mean(grad)
    t_high = alpha * (mu_grad + gamma * sigma_est)
    t_low = beta * t_high
    edges = canny(image, sigma=sigma_g,
                  low_threshold=t_low, high_threshold=t_high)
    return edges, time.time() - start

# Ablation benchmark
ablation_results = {
    'ncc_a': {s: [] for s in [5, 10, 25]},
    'ncc_b': {s: [] for s in [5, 10, 25]},
    'ncc_full': {s: [] for s in [5, 10, 25]},
}

for i, fname in enumerate(img_files[:50]):
    print(f"{i+1}/50", end='\r')
    gt = load_ground_truth(fname, gt_dir)
    if gt is None:
        continue
    img = io.imread(os.path.join(img_dir, fname))
    img_gray_i = color.rgb2gray(img)

    for sigma in [5, 10, 25]:
        noisy = add_gaussian_noise(img_gray_i, sigma)

        edges, _ = ncc_ablation_A(noisy)
        p, r, f = compute_precision_recall(edges, gt)
        ablation_results['ncc_a'][sigma].append(f)

        edges, _ = ncc_ablation_B(noisy)
        p, r, f = compute_precision_recall(edges, gt)
        ablation_results['ncc_b'][sigma].append(f)

        edges, _, _, _, _, _ = noise_calibrated_canny(noisy)
        p, r, f = compute_precision_recall(edges, gt)
        ablation_results['ncc_full'][sigma].append(f)

print("\nAblation tamamlandı!")

# Tabloyu yazdır
print(f"\n{'Yöntem':<15} {'σ=5':>8} {'σ=10':>8} {'σ=25':>8}")
print("-" * 42)
for key, name in [('ncc_a','NCC-A'), ('ncc_b','NCC-B'), ('ncc_full','NCC-Full')]:
    f5  = np.mean(ablation_results[key][5])
    f10 = np.mean(ablation_results[key][10])
    f25 = np.mean(ablation_results[key][25])
    print(f"{name:<15} {f5:>8.4f} {f10:>8.4f} {f25:>8.4f}")

import csv

# Tüm sonuçları CSV'ye kaydet
with open('results_summary.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Method', 'Sigma', 'Precision', 'Recall', 'F-measure'])

    methods = {
        'sobel': 'Sobel',
        'standard_canny': 'Standard Canny',
        'otsu_canny': 'Otsu-Canny',
        'ncc': 'NCC (Proposed)'
    }

    for method_key, method_name in methods.items():
        for sigma in [5, 10, 25]:
            vals = results[method_key][sigma]
            avg_p = np.mean([v[0] for v in vals])
            avg_r = np.mean([v[1] for v in vals])
            avg_f = np.mean([v[2] for v in vals])
            writer.writerow([method_name, sigma,
                           round(avg_p, 4),
                           round(avg_r, 4),
                           round(avg_f, 4)])

# Ablation sonuçlarını da kaydet
with open('ablation_summary.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Method', 'Sigma', 'F-measure'])
    for key, name in [('ncc_a','NCC-A'), ('ncc_b','NCC-B'), ('ncc_full','NCC-Full')]:
        for sigma in [5, 10, 25]:
            avg_f = np.mean(ablation_results[key][sigma])
            writer.writerow([name, sigma, round(avg_f, 4)])

print("CSV dosyaları kaydedildi: results_summary.csv, ablation_summary.csv")

# Görsellerin de kaydedildiğini kontrol et
import os
for fname in ['fmeasure_comparison.png', 'visual_comparison.png']:
    if os.path.exists(fname):
        print(f"✓ {fname} mevcut")
    else:
        print(f"✗ {fname} bulunamadı")

from google.colab import files

files.download('results_summary.csv')
files.download('ablation_summary.csv')
files.download('fmeasure_comparison.png')
files.download('visual_comparison.png')

def plot_precision_recall(results):
    sigma_levels = [5, 10, 25]
    methods = {
        'sobel': 'Sobel',
        'standard_canny': 'Standard Canny',
        'otsu_canny': 'Otsu-Canny',
        'ncc': 'NCC (Proposed)'
    }
    colors = ['blue', 'green', 'orange', 'red']
    markers = ['o', 's', '^', 'D']

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))

    for idx, sigma in enumerate(sigma_levels):
        ax = axes[idx]
        for (method_key, method_name), color, marker in zip(methods.items(), colors, markers):
            vals = results[method_key][sigma]
            avg_p = np.mean([v[0] for v in vals])
            avg_r = np.mean([v[1] for v in vals])
            lw = 2.5 if method_key == 'ncc' else 1.5
            ax.scatter(avg_r, avg_p, color=color, marker=marker, s=100, label=method_name, zorder=5)

        ax.set_xlabel('Recall', fontsize=11)
        ax.set_ylabel('Precision', fontsize=11)
        ax.set_title(f'Precision-Recall (σ={sigma})', fontsize=12)
        ax.legend(fontsize=8)
        ax.set_xlim(0, 1.05)
        ax.set_ylim(0, 0.65)
        ax.grid(True, alpha=0.3)

    plt.suptitle('Precision-Recall Comparison Across Noise Levels', fontsize=13)
    plt.tight_layout()
    plt.savefig('precision_recall.png', dpi=150, bbox_inches='tight')
    plt.show()

plot_precision_recall(results)

files.download('precision_recall.png')

import matplotlib.patches as mpatches
import matplotlib.patheffects as pe

fig, ax = plt.subplots(figsize=(8, 6))
ax.set_xlim(0, 10)
ax.set_ylim(0, 12)
ax.axis('off')

boxes = [
    (5, 11, "Input Image"),
    (5, 9, "Stage 1: Noise Estimation\nσ_est = median(|ε − median(ε)|) / 0.6745"),
    (5, 7, "Stage 2: Adaptive Gaussian Smoothing\nσ_g = k · σ_est,  k=0.5,  σ_g ∈ [0.5, 3.0]"),
    (5, 5, "Stage 3: Gradient Computation\n(Sobel kernels → μ_grad)"),
    (5, 3, "Stage 4: Noise-Proportional Thresholding\nT_high = α·(μ_grad + γ·σ_est),  T_low = β·T_high"),
    (5, 1, "Output: Edge Map"),
]

colors = ['#d0e8ff', '#ffe0b2', '#ffe0b2', '#ffe0b2', '#ffe0b2', '#d4edda']

for (x, y, label), color in zip(boxes, colors):
    fancy = mpatches.FancyBboxPatch((x-3.5, y-0.7), 7, 1.4,
                                     boxstyle="round,pad=0.1",
                                     facecolor=color, edgecolor='#333333',
                                     linewidth=1.5)
    ax.add_patch(fancy)
    ax.text(x, y, label, ha='center', va='center', fontsize=9,
            fontweight='bold' if label in ["Input Image", "Output: Edge Map"] else 'normal')

# Oklar
for i in range(len(boxes)-1):
    x, y_start = boxes[i][0], boxes[i][1] - 0.7
    y_end = boxes[i+1][1] + 0.7
    ax.annotate("", xy=(x, y_end), xytext=(x, y_start),
                arrowprops=dict(arrowstyle="->", color='#333333', lw=1.5))

plt.title("Fig. 3. NCC Pipeline Overview", fontsize=11, pad=10)
plt.tight_layout()
plt.savefig('pipeline_diagram.png', dpi=150, bbox_inches='tight')
plt.show()

files.download('pipeline_diagram.png')

# Hyperparameter sensitivity - alpha etkisi
alphas = [0.6, 0.7, 0.8, 0.9, 1.0]
results_alpha = []

for alpha in alphas:
    f_scores = []
    for fname in img_files[:30]:
        gt = load_ground_truth(fname, gt_dir)
        if gt is None: continue
        img = io.imread(os.path.join(img_dir, fname))
        img_gray_i = color.rgb2gray(img)
        noisy = add_gaussian_noise(img_gray_i, 25)
        edges, _, _, _, _, _ = noise_calibrated_canny(noisy, alpha=alpha)
        _, _, f = compute_precision_recall(edges, gt)
        f_scores.append(f)
    results_alpha.append(np.mean(f_scores))
    print(f"alpha={alpha}: F={np.mean(f_scores):.4f}")

print(results_alpha)

from skimage import color as skcolor
import skimage.io as skio

alphas = [0.6, 0.7, 0.8, 0.9, 1.0]
results_alpha = []

for alpha in alphas:
    f_scores = []
    for fname in img_files[:30]:
        gt = load_ground_truth(fname, gt_dir)
        if gt is None: continue
        img = skio.imread(os.path.join(img_dir, fname))
        img_gray_i = skcolor.rgb2gray(img)
        noisy = add_gaussian_noise(img_gray_i, 25)
        edges, _, _, _, _, _ = noise_calibrated_canny(noisy, alpha=alpha)
        _, _, f = compute_precision_recall(edges, gt)
        f_scores.append(f)
    results_alpha.append(np.mean(f_scores))
    print(f"alpha={alpha}: F={np.mean(f_scores):.4f}")

print(results_alpha)

# Gamma sensitivity
gammas = [1.0, 1.5, 2.0, 2.5, 3.0]
results_gamma = []

for gamma in gammas:
    f_scores = []
    for fname in img_files[:30]:
        gt = load_ground_truth(fname, gt_dir)
        if gt is None: continue
        img = skio.imread(os.path.join(img_dir, fname))
        img_gray_i = skcolor.rgb2gray(img)
        noisy = add_gaussian_noise(img_gray_i, 25)
        edges, _, _, _, _, _ = noise_calibrated_canny(noisy, gamma=gamma)
        _, _, f = compute_precision_recall(edges, gt)
        f_scores.append(f)
    results_gamma.append(np.mean(f_scores))
    print(f"gamma={gamma}: F={np.mean(f_scores):.4f}")

# Beta sensitivity
betas = [0.2, 0.3, 0.4, 0.5, 0.6]
results_beta = []

for beta in betas:
    f_scores = []
    for fname in img_files[:30]:
        gt = load_ground_truth(fname, gt_dir)
        if gt is None: continue
        img = skio.imread(os.path.join(img_dir, fname))
        img_gray_i = skcolor.rgb2gray(img)
        noisy = add_gaussian_noise(img_gray_i, 25)
        edges, _, _, _, _, _ = noise_calibrated_canny(noisy, beta=beta)
        _, _, f = compute_precision_recall(edges, gt)
        f_scores.append(f)
    results_beta.append(np.mean(f_scores))
    print(f"beta={beta}: F={np.mean(f_scores):.4f}")

fig, axes = plt.subplots(1, 3, figsize=(15, 5))

# Alpha
axes[0].plot(alphas, results_alpha, 'o-', color='royalblue', linewidth=2, markersize=8)
axes[0].axvline(x=0.9, color='red', linestyle='--', alpha=0.7, label='Selected (0.9)')
axes[0].set_xlabel('α', fontsize=12)
axes[0].set_ylabel('F-measure (σ=25)', fontsize=11)
axes[0].set_title('Sensitivity to α', fontsize=12)
axes[0].legend(fontsize=9)
axes[0].grid(True, alpha=0.3)
axes[0].set_ylim(0.42, 0.46)

# Gamma
axes[1].plot(gammas, results_gamma, 's-', color='darkorange', linewidth=2, markersize=8)
axes[1].axvline(x=2.0, color='red', linestyle='--', alpha=0.7, label='Selected (2.0)')
axes[1].set_xlabel('γ', fontsize=12)
axes[1].set_ylabel('F-measure (σ=25)', fontsize=11)
axes[1].set_title('Sensitivity to γ', fontsize=12)
axes[1].legend(fontsize=9)
axes[1].grid(True, alpha=0.3)
axes[1].set_ylim(0.40, 0.46)

# Beta
axes[2].plot(betas, results_beta, '^-', color='green', linewidth=2, markersize=8)
axes[2].axvline(x=0.4, color='red', linestyle='--', alpha=0.7, label='Selected (0.4)')
axes[2].set_xlabel('β', fontsize=12)
axes[2].set_ylabel('F-measure (σ=25)', fontsize=11)
axes[2].set_title('Sensitivity to β', fontsize=12)
axes[2].legend(fontsize=9)
axes[2].grid(True, alpha=0.3)
axes[2].set_ylim(0.43, 0.46)

plt.suptitle('Hyperparameter Sensitivity Analysis (σ=25)', fontsize=13)
plt.tight_layout()
plt.savefig('hyperparam_sensitivity.png', dpi=150, bbox_inches='tight')
plt.show()

files.download('hyperparam_sensitivity.png')